### ISSUE TITLE
Scopes field included in the request even if scopes list is empty

### ISSUE THREAD

**Issue by vladostaci** [googleapis/google-oauth-java-client#494]
https://github.com/googleapis/google-oauth-java-client/blob/7b5f86a456bcf1b6477809599924c3e3cb558c6a/google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/TokenRequest.java#L225

There's a bug in `TokenRequest.setScopes` which sets the scopes to an empty string when the scopes list is empty.

The workaround:
```
  public TokenRequest setScopes(Collection<String> scopes) {
    this.scopes = (scopes == null || scopes.isEmpty()) ? null : Joiner.on(' ').join(scopes);
    return this;
  }
```

Some APIs aren't supporting scopes, so the request will fail.

**Comment by chingor13** [comment]
Added a failing test case in #640. @silvolu I'm having a hard time finding whether this proposed behavior is correct or not.

**Comment by silvolu** [comment]
The [spec](https://tools.ietf.org/html/rfc6749#section-3.3) says that a client can omit the scope parameter and that the value of the scope parameter is expressed as a list of space-delimited, case-sensitive strings defined by the authorization server, but it doesn't explicitly say it should be non-empty.

Given that, I'd rather not change the existing behavior; @vladostaci to omit the scope parameter, you should pass a null value instead of an empty list.

**Comment by chingor13** [comment]
In that case, I can change #640 to add the test that explicitly ensures the empty scope parameter when provided an empty list

**Comment by vovahost** [comment]
@silvolu We need to change https://github.com/googleapis/google-oauth-java-client/blob/dfc43f709859928f1e6019c39f250ab54f5e33c1/google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/AuthorizationCodeFlow.java#L863 so it allows null values.

Also here https://github.com/googleapis/google-oauth-java-client/blob/dfc43f709859928f1e6019c39f250ab54f5e33c1/google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/AuthorizationCodeFlow.java#L162
